"""empty message

Revision ID: 526362ee8c82
Revises: 
Create Date: 2021-08-01 13:26:59.479926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526362ee8c82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_key', sa.Column('days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_key', 'days')
    # ### end Alembic commands ###
