"""empty message

Revision ID: 6a98c0a01f85
Revises: 
Create Date: 2021-07-28 19:41:30.462964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a98c0a01f85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_key', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_key', 'is_active')
    # ### end Alembic commands ###
