"""empty message

Revision ID: 7dfb2a32e022
Revises: 
Create Date: 2021-08-01 21:13:31.692497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfb2a32e022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_key', 'days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_key', sa.Column('days', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
