"""empty message

Revision ID: a35e462f9a7c
Revises: 526362ee8c82
Create Date: 2021-08-01 13:41:28.765989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35e462f9a7c'
down_revision = '526362ee8c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_key', 'days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_key', sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
