"""empty message

Revision ID: cf823e0664f4
Revises: a35e462f9a7c
Create Date: 2021-08-01 13:47:32.542666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf823e0664f4'
down_revision = 'a35e462f9a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_key', sa.Column('days', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_key', 'days')
    # ### end Alembic commands ###
